# Generated by Django 4.2.3 on 2023-07-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littlelemonApp", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu", name="description", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="menu", name="name", field=models.CharField(max_length=20),
        ),
    ]
