# Generated by Django 4.2.3 on 2023-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littlelemonApp", "0003_menu_description_alter_menu_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["number_of_person"], name="Booking_number__05e40c_idx"
            ),
        ),
    ]
