# Generated by Django 4.2.3 on 2023-08-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("littlelemonApp", "0004_booking_booking_number__05e40c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu", name="inventory", field=models.IntegerField(default=1),
        ),
    ]
