# Generated by Django 4.2.3 on 2023-08-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("littlelemonApp", "0007_menu_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="littlelemonApp.category",
            ),
        ),
    ]
