# Generated by Django 4.2.3 on 2023-08-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("littlelemonApp", "0008_alter_menu_category"),
    ]

    operations = [
        migrations.RenameModel(old_name="Menu", new_name="MenuItem",),
    ]
